
trigger: none

pool: Soumya


steps:
 

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
    backendServiceArm: 'Soumya_spn'
    backendAzureRmStorageAccountName: 'backednsoumyastg'
    backendAzureRmContainerName: 'soumyatfstate'
    backendAzureRmKey: 'terraform.tfstate'